spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://127.0.0.1:3306/maplestory_079?autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  config:
    import: server.properties, fish.properties, shop.properties
